services:
  web:
    build: .
    container_name: bulletinboard_django
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - ./cache_files:/app/cache_files
      - ./db.sqlite3:/app/db.sqlite3
    env_file:
      - ./bulletinboard/.env
    environment:
      - DJANGO_SETTINGS_MODULE=bulletinboard.settings
      - PYTHONUNBUFFERED=1
    networks:
      - bulletinboard_network

  celery:
    build: .
    container_name: bulletinboard_celery
    restart: unless-stopped
    command: celery -A bulletinboard worker --loglevel=info
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    env_file:
      - ./bulletinboard/.env
    environment:
      - DJANGO_SETTINGS_MODULE=bulletinboard.settings
      - PYTHONUNBUFFERED=1
    networks:
      - bulletinboard_network

  celery-beat:
    build: .
    container_name: bulletinboard_celery_beat
    restart: unless-stopped
    command: celery -A bulletinboard beat --loglevel=info
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    env_file:
      - ./bulletinboard/.env
    environment:
      - DJANGO_SETTINGS_MODULE=bulletinboard.settings
      - PYTHONUNBUFFERED=1
    networks:
      - bulletinboard_network

networks:
  bulletinboard_network:
    driver: bridge